


<div class="Container" style="text-align: justify;"  >
    <div style="padding:0 20px;">
<p> <b> <u> Test Purchase Agreement: </u> </b> </p> 

 <p>YOU AND TECNETO LLC, AGREE THAT YOUR PURCHASE OF ANY RIGHTS TO TAKE THE TECNETO LLC TEST ONLINE (AN "ONLINE TEST"), IS SUBJECT TO YOUR AGREEMENT TO THE TERMS AND CONDITIONS LISTED BELOW, WHICH WILL BECOME A BINDING AGREEMENT BETWEEN YOU AND TECNETO LLC (THE "AGREEMENT"). PLEASE READ THESE TERMS CAREFULLY. AFTER READING THE TERMS, IF YOU AGREE TO THEM, PLEASE INDICATE YOUR DECISION BY CLICKING ON "I AGREE" AT THE END OF THIS AGREEMENT. IF YOU DO NOT AGREE, INDICATE YOUR DECISION BY CLICKING ON "I DO NOT AGREE" AND YOU WILL BE RETURNED TO THE HOME PAGE OF THIS WEB SITE. IN ADDITION, IF YOU DO NOT AGREE WITH THESE TERMS, TECNETO LLC WILL REFUND ANY AMOUNTS THAT YOU HAVE PREPAID FOR ONLINE TESTS. ALL PURCHASES OF ONLINE TESTS WILL BE A PURCHASE OF A RIGHT TO TAKE THE ONLINE TEST ONLY AND NOT A PURCHASE OF THE ACTUAL ONLINE TEST CONTENT OR SOFTWARE. BY PURCHASING THE RIGHTS TO ONE OR MORE ONLINE TESTS, YOU AGREE TO THE FOLLOWING TERMS AND CONDITIONS.
</p><br>
<p>1.	Online Tests. Subject to the following terms and conditions, TECNETO LLC grants to you a nonexclusive, nontransferable right to take or assign your employees to take that number of Online Tests for which you have paid TECNETO LLC the required fee. Your right to access and take Online Tests is limited to that number of Online Tests that you have purchased and it is your responsibility to track and record the number of Online Tests purchased. You can determine the number of test takings remaining by clicking the SUBSCRIPTION SUMMARY  button on the Dashboard screen and following the directions. YOUR RIGHT TO TAKE THE ONLINE TESTS AUTOMATICALLY TERMINATES ON THE FIRST TO OCCUR OF: (i) THE DATE ONE YEAR FROM THE DATE OF PURCHASE OF THE ONLINE TESTS, OR (ii) WHEN THE NUMBER OF TIMES YOU HAVE USED YOUR PASSWORD TO ACCESS AN ONLINE TEST EQUALS THE NUMBER OF ONLINE TESTS THAT YOU HAVE PURCHASED. THE DATE OF TERMINATION IS REFERRED TO HEREIN AS THE "EXPIRATION DATE". AS OF THE EXPIRATION DATE, ALL RIGHTS THAT YOU MAY HAVE TO TAKE ONLINE TESTS WILL TERMINATE. THERE ARE NO REFUNDS PROVIDED FOR ONLINE TESTS NOT TAKEN AS OF THE EXPIRATION DATE. BY WAY OF ILLUSTRATION AND EXAMPLE, IF YOUR RIGHT TO TAKE 200 ONLINE TESTS EXPIRES AS OF DECEMBER 31 AND ON THE IMMEDIATELY FOLLOWING JANUARY 1, YOU HAVE ONLY TAKEN 150 ONLINE TESTS, YOU WILL HAVE FORFEITED ALL RIGHTS WITH RESPECT TO 50 ONLINE TESTS AND NO REFUNDS WILL BE PROVIDED WITH RESPECT TO SUCH TESTS. The Online Tests that you purchase are subject to copyright and other proprietary rights protection. You agree that you will not violate any of those copyright or other proprietary rights and that you will comply with all applicable laws and regulations. Your right to take Online Tests is in no way intended, and shall not be interpreted, to grant to you any rights permitting you to: (x) translate, alter, copy, revise, modify, change, or create derivative works based on the Online Tests in whole or in part; (y) publish, display, distribute, sell, rent, or otherwise make the Online Test, in whole or in part, available to any third party; or (z) print or otherwise reproduce the Online Test for distribution, in whole or in part. TECNETOLLC’s policy is one of on-going update and revision. TECNETO LLC may revise or discontinue an Online Test at any time. Your purchase of the right to an Online Test entitles you to solely to take an Online Test that is available at the time of taking and not the right to take any future updated or revised Online Test.
</p><br><p>
2.	Ownership. This license is not a sale. Title, ownership rights, and intellectual property rights in and to the Online Tests shall remain in TECNETO LLC. You agree to abide by the copyright laws and all other applicable laws of the United States. Failure to comply with the above restrictions will result in automatic termination of this Agreement and will make available to TECNETO LLC other legal remedies.
</p><br><p>
3.	Payment Terms. You agree to pay TECNETO LLC as indicated and agreed to by you on the Online Tests order form. All payments are nonrefundable once you indicate your agreement with this Volume Purchase Agreement and these terms.
</p><br><p>
4.	Warranty. TECNETO LLC MAKES NO WARRANTIES, EXPRESS OR IMPLIED, WITH RESPECT TO THE ONLINE TESTS AND SPECIFICALLY DISCLAIMS THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. TECNETO LLC DOES NOT WARRANT THAT THE USE OF THE ONLINE TESTS WILL BE UNINTERRUPTED OR ERROR FREE. THE ONLINE TEST IS PROVIDED AS-IS AND AS-AVAILABLE. NO LIABILITY IS ASSUMED FOR IMPROPER USE OF AN ONLINE TEST OR THE RESULTS THEREFROM.
</p><br><p>
5.	Limitation of Liability. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL TECNETO LLC BE LIABLE FOR ANY SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES WHATSOEVER, INCLUDING ANY CLAIMS FOR LOST PROFITS, BUSINESS INTERRUPTION, LOST INFORMATION OR OTHER DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE ONLINE TESTS. IN ALL EVENTS, TECNETO LLC'S SOLE OBLIGATION OR LIABILITY UNDER THIS AGREEMENT IN THE AGGREGATE IS THE REPLACEMENT OF THE ONLINE TESTS OR A REFUND OF THE PURCHASE PRICE PAID FOR THE ONLINE TESTS. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. TECNETO LLC IS NOT RESPONSIBLE FOR CORRECTING ANY ERROR IN THE ONLINE TESTS.
</p><br><p>
6.	Covenant Not to Sue and Waiver. You hereby agree not to sue, assist in or be a voluntary party to assist in or be a voluntary party to, except as required by law, any action, suit, or proceeding against TECNETO LLC for any claims, actions, suits, damages, liability, losses or expenses of whatever kind or however arising out of or relating to your use of the Online Tests. You further hereby waive any and all rights you may have to sue, assist in or be a voluntary party to, except as required by law, any action, suit, or proceeding against TECNETO LLC for any claims, actions, suits, damages, liability, losses or expenses of whatever kind or however arising out of or relating to your use of the Online Tests. You agree to defend, indemnify and hold harmless TECNETO LLC, its officers, directors, employees, agents, successor and assigns from and against any suits losses, claims, demands, liabilities, costs and expenses, including reasonable attorneys' fees, that they may sustain or incur as a result of any claim against them based upon your use of the Online Tests.
</p><br><p>
7.	Cancellation. TECNETO LLC may terminate this Agreement immediately and without notice if you fail to comply with any term or condition of this Agreement. In the event of termination of this Agreement, all the sections of this Agreement will survive except for the section entitled "Online Tests."
</p><br><p>
BY CLICKING ON THE "I ACCEPT" BUTTON BELOW, YOU ACKNOWLEDGE THAT YOU HAVE READ THIS AGREEMENT, THAT YOU UNDERSTAND IT, AND THAT YOU AGREE TO BE BOUND BY ITS TERMS. Copyright 2011 TECNETO LLC, Inc. All Rights Reserved.
</p>
    </div>
</div>